### ISSUE TITLE
ISO Date parsing in 0.8.3 fails with certain formats

### ISSUE THREAD

**Issue by krraghavanai** [krraghavan/mongodb-aggregate-query-support#49]
ISO Date parsing is broken when the date is in the following format: "2024-06-27T10:12:18.649Z"

Looks like the library expects comma before msecs: yyyy-MM-dd'T'HH:mm:ss,SSS'Z'

https://github.com/krraghavan/mongodb-aggregate-query-support/commit/68f0f49cbea0b773a10d044b322054c800f001f2

 

Should it be dot?

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/format/annotation/DateTimeFormat.ISO.html#DATE_TIME

---
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Only ISO date format (with or without msecs) is supported.  Could not deserialize 2024-06-27T10:12:18.649Z (through reference chain: com.cisco.ni.config.domain.ag.AlertRule["lastModifiedTime"])

at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)

at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)

at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1826)

at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:316)

at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)

at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)

at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)

at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)

at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3645)

at com.github.krr.mongodb.aggregate.support.query.MongoNativeJavaDriverQueryExecutor.deserialize(MongoNativeJavaDriverQueryExecutor.java:247)

... 165 more

Caused by: java.lang.UnsupportedOperationException: Only ISO date format (with or without msecs) is supported.  Could not deserialize 2024-06-27T10:12:18.649Z

at com.github.krr.mongodb.aggregate.support.deserializers.BsonDateToDateDeserializer.doDeserialize(BsonDateToDateDeserializer.java:50)

at com.github.krr.mongodb.aggregate.support.deserializers.BsonDateToDateDeserializer.doDeserialize(BsonDateToDateDeserializer.java:16)

at com.github.krr.mongodb.aggregate.support.deserializers.GenericMongoExtendedJsonDeserializer.deserialize(GenericMongoExtendedJsonDeserializer.java:45)

at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)

at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)

... 171 more

Caused by: java.text.ParseException: Unparseable date: "2024-06-27T10:12:18.649Z"

at java.base/java.text.DateFormat.parse(Unknown Source)

at com.github.krr.mongodb.aggregate.support.deserializers.BsonDateToDateDeserializer.doDeserialize(BsonDateToDateDeserializer.java:41)

**Comment by krraghavan** [comment]
Fixed in 0.9.3
